#elem-brief: video interface management
#elem-version: 1.0
#elem-type:VIDEO
#elem-author:Heero Yui<yui.heero@gmail.com>

vector:string getAlbums()
vector:string getSubAlbums(string)
uint32 getAlbumCount(string)
vector:string getAlbumListPicture(string)
//zeus::FileServer getAlbumPicture(string)
//string addFile(zeus::File)
bool removeFile(string)
/*
string createAlbum(string)
bool removeAlbum(string)
bool setAlbumDescription(string, string)
string getAlbumDescription(string)
bool addInAlbum(string, string)
bool removeFromAlbum(string, string)
*/