#elem-brief: picture interface management
#elem-version: 1.0
#elem-type:PICTURE
#elem-author:Heero Yui<yui.heero@gmail.com

import zeus-File

// ----------------- Get media with their ID -----------------------
#brief:Get the number of media availlable (a media is a picture or a video)
#return: Number of media
uint32 mediaIdCount()

#brief:Get range list of media ids in a specific range (<1024)
#param:start:First Id of the media stream requested (range [0..+inf[)
#param:stop:Last Id of the media stream requested (excluded) (range [0..+inf[)
#return:List of the media Ids
vector:uint32 mediaIdGetRange(uint32,uint32)

// ----------------- media Access -----------------------
#brief:Get a media
#param:mediaId:Id of the media
#return:A file reference on the media (transmission is async)
obj:zeus-File mediaGet(uint32)
/*
#brief:Get a media in STREAM mode (usefull for video)
#param:mediaId:Id of the media
#return:A stream reference on the media (transmission is async)
obj::zeus-Stream mediaStream(uint32)
*/
#brief:Add a new media in the service
#param:data:A file reference on the media (transmission is async)
#return:Local personal ID of the media
uint32 mediaAdd(obj:zeus-File)

#brief:Remove a media in the service (no trash)
#param:mediaId:Id of the media
void mediaRemove(uint32)

// ----------------- meta-data Access -----------------------
/*
#brief:Get all meta-data of a media
#param:mediaName:Name of the media
#return:a json description of the metadata
json mediaMetadataGet(string)
*/

#brief:Get all meta-data keys of a media
#param:mediaId:Id of the media
#return:List of all availlable keys
vector:string mediaMetadataGetKeys(uint32)

#brief:Get a meta-data value of a key
#param:mediaId:Id of the media
#param:key:Key of the meta-data
#return:data in the key
string mediaMetadataGetKey(uint32, string)

#brief:Set a meta-data value of a key
#param:mediaId:Id of the media
#param:key:Key of the meta-data
#param:value:data in the key
void mediaMetadataSetKey(uint32, string, string)

/*
#brief:Set all meta-data of a media
#param:name:Name of the media
#param:description: a json description of the metadata
void mediaMetadataGet(string, json)
*/

// ----------------- Album Access -----------------------
#brief: Create an album
#param:albumName:Name of the Album
#return:Id of the album
uint32 albumCreate(string)

#brief: Remove an album
#param:albumId:Id of the Album
void albumRemove(uint32)

#brief:Get list of Id of all albums
#return:List of all Id of the albums
vector:uint32 albumGetList()

#brief:Get the name of the album
#param:albumId:Id of the Album
#return:Name of the Album
string albumNameGet(uint32)

#brief:Set the name of the album
#param:albumId:Id of the Album
#param:albumName:Name of the Album
void albumNameSet(uint32, string)

#brief:Get the description of the album
#param:albumId:Id of the Album
#return:Description of the Album
string albumDescriptionGet(uint32)

#brief:Set the description of the album
#param:albumId:Id of the Album
#param:desc:Description of the Album
void albumDescriptionSet(uint32, string)

#brief:Add a media in an album
#param:albumId:Id of the Album
#param:mediaId:Id of the media to add
void albumMediaAdd(uint32, uint32)

#brief:Remove a media in an album
#param:albumId:Id of the Album
#param:mediaId:Id of the media to remove
void albumMediaRemove(uint32, uint32)

#brief:Get number of media in an album
#param:albumId:Id of the Album
#return:Number of medias
uint32 albumMediaCount(uint32)

#brief:Get list of name of the media in a specific range (<1024)
#param:albumId:Id of the Album
#param:start:First Id of the media stream requested (range [0..+inf[)
#param:stop:Last Id of the media stream requested (excluded) (range [0..+inf[)
#return:List of the media Ids
vector:uint32 albumMediaIdGet(uint32, uint32,uint32)

#brief:Set the parrent album at a specific album
#param:albumId:Id of the Album
#param:albumParentId:Id of the parent Album
void albumParentSet(uint32, uint32)

#brief:Remove the parrent album at a specific album
#param:albumId:Id of the Album
void albumParentRemove(uint32)

#brief:Get the parrent album at a specific album
#param:albumId:Id of the Album
uint32 albumParentGet(uint32)

// ----------------- Album Right Access -----------------------


// ----------------- Media Right Access -----------------------

