#srv-brief: user interface management
#srv-version: 1.0
#srv-type:USER
#srv-author:Heero Yui<yui.heero@gmail.com>

// Idl comment example

/*
Multiple line comment example
And an other line
*/

#brief:Get list of group availlable for a client name
#param:clientName:Name of the client
vector:string getGroups(string)

#brief:Check if a user tocken is correct or not
#param:clientName:Name of the client
#param:tocken:String containing the Tocken
#return: true if the Tocken is validated or false if it is wrong
bool checkTocken(string, string)

#brief:Check the password of the curent user
#param:password:client/user password
#return: true if the pasword is validated or false if it is wrong
bool checkAuth(string)

#brief:Filter a list of service with the cuurent profile of the user (restrict area)
#param:clientName:Name of the client
#param:currentList:Vector of name of the services
vector:string filterServices(string, vector:string)
